FROM arm32v7/python:3.6-alpine3.9

LABEL maintainer="Kyunghan (Paul) Lee <enigma@enigmatic.network>"

WORKDIR /app

COPY . /app

RUN pip install --trusted-host pypi.python.org -r requirements.txt

CMD ["python", "bot.py"]
